name: Sync rcore-os to gitee 

on:
  schedule:
    - cron: '30 16 * * *'	# Beijing Time 00:30

jobs:
  gitee:
    runs-on: ubuntu-20.04
    steps:

    - name: Sync Github Repos To Gitee  
      uses: shzhxh/hub-mirror-action@master
      with:
        src: github/rcore-os	# 源端账户名(github)
        dst: gitee/rcore-os  # 目的端账户名(gitee)
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
        account_type: org  # 账户类型
        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        timeout: '600s'  # git超时设置，超时后会自动重试git操作

